services:
  postgres:
    image: postgres:18
    container_name: quack_postgres
    restart: always
    environment:
      POSTGRES_USER: duck
      POSTGRES_PASSWORD: quack
      POSTGRES_DB: quack
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: quack_redis
    restart: always
    ports:
      - '6379:6379'
    command: ["redis-server", "--save", "900", "1", "--loglevel", "warning"]

  scylla:
    image: scylladb/scylla:latest
    container_name: quack_scylla
    restart: always
    ports:
      - '9042:9042'
      - '9160:9160'
      - '9180:9180'
    command: --smp 1 --memory 512M --overprovisioned 1

volumes:
  pgdata:
